-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Topics
CREATE TABLE IF NOT EXISTS topics (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Agents
CREATE TABLE IF NOT EXISTS agents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    bio TEXT NOT NULL,
    voice_id TEXT NOT NULL, -- ElevenLabs Voice ID
    provider TEXT NOT NULL, -- 'grok', 'claude', 'gemini', 'openai'
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Conversations
CREATE TABLE IF NOT EXISTS conversations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agent_1_id UUID REFERENCES agents(id),
    agent_2_id UUID REFERENCES agents(id),
    status TEXT DEFAULT 'scheduled', -- 'scheduled', 'active', 'completed'
    topic_id UUID REFERENCES topics(id),
    topic_title TEXT, -- Denormalized for easy access
    full_conversation TEXT, -- Stored as a large text block or JSON string for quick context loading
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Turns (The granular dialogue lines)
CREATE TABLE IF NOT EXISTS turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE,
    turn_number INT NOT NULL,
    agent_id UUID REFERENCES agents(id),
    text TEXT, -- The logic text response
    audio_url TEXT, -- The 11Labs generated audio
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Consensus Reports (Final Summary)
CREATE TABLE IF NOT EXISTS consensus_reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    topic_id UUID REFERENCES topics(id),
    narrative_text TEXT,
    audio_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Realtime for critical tables (Essential for the UI to update dynamically)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'conversations') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE conversations;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'turns') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE turns;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'topics') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE topics;
    END IF;
END $$;
